### ISSUE TITLE
CLI should be a plugin to `honeybee` cli

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-radiance#23]
I think we should use [click plugins](https://github.com/click-contrib/click-plugins) to register commands from `honeybee-radiance` under the main `honeybee` command.

In practice this means that instead of running something like:
```console
~$ honeybee-radiance 
Successfully imported Ladybug plugin: ladybug_geometry
Usage: honeybee-radiance [OPTIONS] COMMAND [ARGS]...

  honeybee radiance commands.

Options:
  --help  Show this message and exit.

Commands:
  grid  Commands for generating and modifying sensor grids.
  sky   Commands to generate Radiance skies.
```

You would be able to call the `honeybee-radiance` package from within the `honeybee` CLI:

```console
~$ honeybee 
Usage: honeybee [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  viz            Check if honeybee is flying!
  radiance   Honeybee-Radiance plugin commands


~$ honeybee radiance
Usage: honeybee radiance [OPTIONS] COMMAND [ARGS]...

  honeybee radiance commands.

Options:
  --help  Show this message and exit.

Commands:
  grid  Commands for generating and modifying sensor grids.
  sky   Commands to generate Radiance skies.
```

**Comment by mostaphaRoudsari** [comment]
Maybe I don't understand the issue here but if I understand correctly this is how it has been set-up right now. We don't use the plugin but it works very similar. You can either use `honeybee-radiance` or `honeybee radiance` and they will both work just like what you have posted up there.

**Comment by mostaphaRoudsari** [comment]
![image](https://user-images.githubusercontent.com/2915573/70017995-b536f200-1552-11ea-8213-6f332fcc22c0.png)

**Comment by AntoineDao** [comment]
Huh... you're totally right it works exactly like that already. My bad :smile:
