### ISSUE TITLE
Add a model_to_rad_folder method to the honeybee-radiance writer

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#34]
This will need some methods to group opaque and nonopaque model elements, which we can implement on the Model at staticmethods or as separate utility functions (not sure if one is better than the other but I might make a judgement call based on how long the code ends up being).

It's also going to need methods to get all of the unique modifiers of these groups while replacing any object with overridden `modifier_blk` with a duplicate that has 2 new modifiers of matching name (so that they can abide by the system @mostaphaRoudsari set up in the Radiance folder structure where the .blk modifiers need to have the same name as the .mat modifiers). These new;y-created matching blk and non-lbk modifiers should get added to special lists. 

While we're iterating, we'll collect any unique modifiers of non-overridden blk objects in their own list. Then, we'll generate blk modifiers from these collected unique modifiers.

**Comment by chriswmackey** [comment]
This is being addressed via https://github.com/ladybug-tools/honeybee-radiance/pull/66

**Comment by mostaphaRoudsari** [comment]
That was super quick @chriswmackey! Very excited to give it a try. 🎉🎉🎉
