### ISSUE TITLE
Add states to Shades, Apertures and Doors

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#35]
We need to add states to the radiance properties of Shades, Apertures, and Doors in order to simulate dynamic geometry.

Each state should be a full definition of an object in its new state (eg. another Shade, Aperture, Door, and Face). These other states can have their own geometry, modifier, and child objects)

Within the state property setter, we will have to enforce that a state object doesn't have a parent and doesn't have states itself. We will also need to make sure that that all assigned child objects to a state do not have states.

**Comment by chriswmackey** [comment]
I just wanted to post an explanation of what I finally plan to implement after a long deliberation of options, followed by a long discussion with @mostaphaRoudsari , followed by and another long deliberation about whether certain things should go into honeybee-core vs. honeybee-energy.

I have come to the conclusion that dynamic objects are different enough between EnergyPlus and Radiance that we should implement all objects/properties related to them under extension properties rather than core objects.  While we will be able to write translation methods between Radiance and Energy dynamic objects, dynamic objects in these two engines have fundamental differences:

- In EnergyPlus, you need to know the control logic for the dynamic behaviour before running the simulation whereas, for Radiance, you develop the control logic after the simulation is run. So, for one engine, control logic is an input while, for the other, it’s an output.
- EnergyPlus does not care how Apertures or Shades are grouped since any grouping behaviour is already accounted for in the control logic. So the group information is redundant/superfluous in EnergyPlus.
- In EnergyPlus, you need a Construction to identify a state while, in Radiance, you need a Modifier.

So making an object dynamic in Radiance is not enough info to make it dynamic in EnergyPlus though the inverse is true. To go from Radiance to EnergyPlus, you need to input a control logic and you need to specify what Constructions the Modifiers correspond to.

So this is what I am thinking of implementing here in honeybee-radiance:
![Honeybee-radiance dynamic geometry](https://user-images.githubusercontent.com/5567574/79671400-ffcea900-8197-11ea-8480-b94e84c50c45.png)

... and this is the parallel structure I am thinking of implementing in honeybee-energy:
![Honeybee-radiance dynamic geometry (1)](https://user-images.githubusercontent.com/5567574/79671410-1543d300-8198-11ea-84bf-d9f328774ca5.png)


This is essentially the same thing that @mostaphaRoudsari and I agreed on at the end of our call with one tweak: we use a common string identifier to group Apertures into the same ApertureGroup rather than creating a whole new ApertureGroup object that we need to add the Apertures to.  There are a number of reasons why this is a mush more elegant solution:

- We never have to worry about cases where only some of the Apertures of a group are added to the model. If the Aperture isn’t in the model, it isn’t in the groups the Model exports. So everything still works and those Apertures of the group that are in the Model still get grouped together.
- We never have to worry about what happens when you duplicate the Aperture. If the ApertureGroup were some object sitting above the Aperture, then duplicating it or duplicating its parent Face would divorce the Aperture from the original group, much like duplicating the Aperture on its own divorces it from its parent Face.  This means the aperture group couldn’t carry over between Grasshopper components that copy the honeybee objects.
- We used the same strategy (identifiers instead of object references) for Surface boundary_condition_objects, which are similarly like a network logic sitting above the geometry objects. This has been working well for this case.
- We don’t have to worry about re-serializing the ApetureGroup from a dictionary since the group is embedded in the geometry objects themselves.
- We can still have a read-only property on the Model that returns ApertureGroup objects that lets you do things like count the total number of states in each group, get aligned properties for the objects in the group, etc.. But this property will be generated on the fly from the Apertures in the Model.

Ultimately, here are the rules that I plan to implement in honeybee-radiance for dynamic objects:

- An Aperture becomes dynamic (going into the dynamic folder) if it has a dynamic_group_identifier or if it is has states. Typically, you will want all of the Apertures with the same dynamic_group_identifier to have the same number of states such that these aligned states change in unison but this is not required.
- If there is a mismatch in the number of states for the Apertures with the same dynamic_group_identifier, a “longest list” logic will be applied. So the total number of states for the dynamic_group is equal to the number of states in the Aperture with the highest number of states. After 
- If an Aperture has a dynamic_group_identifier but no states, it will remain in its default state, essentially behaving like static geometry but it will be written into each of the rad files for the dynamic_group.
- If an aperture has states but no dynamic_group_identifier, the aperture will be presumed to be in a group of its own where it is the only aperture in the group.

**Comment by mostaphaRoudsari** [comment]
Hi @chriswmackey. The graphs look great and I agree with your decisions.

My only minor comment is about the last item in your list:

> If an aperture has states but no dynamic_group_identifier, the aperture will be presumed to be in a group of its own where it is the only aperture in the group.

I prefer this not to exist. Why would you think such a case will be useful? I think every aperture group should have an identifier.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I am fine with enforcing that every object that has states needs to have a `dynamic_group_identifier`. So we'll just raise an exception if someone goes to assign a state without first specifying a `dynamic_group_identifier`.

The only reason why I originally thought it was useful was because, on the UI end, I imagine people might want to apply states to a bunch of Apertures as they create the Apertures. Then, they can join all of those Apertures into the same dynamic group. This way you can set up some of the apertures in the group to have X modifier in a certain state while other apertures in the group have Y modifier in the same state.

But, now that I think about it, we can still enforce that all objects with sates have a  `dynamic_group_identifier` in the core but just take care of the auto-generation of a `dynamic_group_identifier` on the UI end. After all, if you are applying the same set of states to a bunch of Apertures when you create them, you probably want them to all be in the same dynamic group more often than you want each aperture to be in its own separate dynamic group. So I think we will just set up the Grasshopper UI to auto-generate a name for the dynamic group if the users supplies states when they create apertures from a list of breps/meshes. Then, they have the option to overwrite the dynamic group of a set of aperture together using another component, essentially allowing them to combine aperture groups together or add static apertures into the group. And, if someone really needs each aperture of a list to be its own dynamic group when they create it, they can use data trees or multiple aperture components to do so.

**Comment by chriswmackey** [comment]
Here are the new set of rules that will be enforced:

- An Aperture becomes dynamic (going into the dynamic folder) if it has a dynamic_group_identifier. States cannot be assigned to an Aperture unless it has a dynamic_group_identifier. Typically, you will want all of the Apertures with the same dynamic_group_identifier to have the same number of states such that these aligned states change in unison but this is not required.
- If there is a mismatch in the number of states for the Apertures with the same dynamic_group_identifier, a “longest list” logic will be applied. So the total number of states for the dynamic_group is equal to the number of states in the Aperture with the highest number of states. After 
- If an Aperture has a dynamic_group_identifier but no states, it will remain in its default state, essentially behaving like static geometry but it will be written into each of the rad files for the dynamic_group.


I also want to outline the rules that govern Radiance States:
- ApertureStates are defined by Radiance modifier (required) and additional shade geometry (optional).
- An ApertureState can have only one parent Aperture. This way, the ApertureState dictionary appears underneath the Aperture's Radiance properties dictionary in the schema (it's not like you find just the id of an aperture state under this Aperture, which corresponds to a reference elsewhere in the model).  This also means we don't have to lock the state when we apply it to an aperture since editing the state will only change that state and not other Apertures across a model. This will also help ensure that people don't add a bunch of shades intended for multiple apertures to one state and then apply that state to several apertures, effectively resulting in duplicate shades written into the rad file. The user needs to consciously decide which shades are assigned to which aperture or, if they want to lump all of the shades of a dynamic_group into one state, they just pick one of the apertures to carry the shades in their state.
- ApertureStates, themselves, do not need identifiers since they are effectively defined by the dynamic_group_identifier of the aperture that they are a part of and the index of where they appear in the states list.
- For a honeybee shade to be assigned to an ApertureState, it must be orphaned (possess no parent Room or Face), it must not have a `dynamic_group_identifier` itself (you can't have a dynamic shade assigned to a dynamic aperture), and it cannot already be assigned to another ApertureState.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/honeybee-radiance/pull/77
