### ISSUE TITLE
Add the option to specify units for grid-size and offset.

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#476]
According to @mostaphaRoudsari ...

> I'm just talking about accepting units as part of the input
> like 4m, 2cm, 3ft and so on
> I know Andrew put a component together in Grasshopper that does the same
> so user can say --grid-size 0.5m
> or --grid-size 3ft
> if no unit is provided then the units from the model will be used
> that will allow us to have a fixed default input while making it easy for users to use the unit of their HB model

It seems like this will give us the best of both worlds.

While I am at it, I should also add a `--remove-out` option to the grid commands.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, I believe this has been already addressed. I'm closing it but feel free to open it if it is still an open issue.
