### ISSUE TITLE
allow "model" input as json string not a file path to json

### ISSUE THREAD

**Issue by ksobon** [ladybug-tools/honeybee-radiance#478]
@chriswmackey tell me if this is stupid but at the moment I have to serialize the whole model into a json string, then submit it to `honeybee-radiance grid from-rooms modelFilePath` call. Once I do that I have to potentially re-serialize it again if user actually wanted to export a json model to begin with. Any way to avoid this, by just feeding a HBJSON string as an argument directly to the call?

**Comment by chriswmackey** [comment]
Given that we discussed this on Basecamp, do you think we can close this out @ksobon ?
