### ISSUE TITLE
Add a command to postprocess results into light-dimming schedules

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#488]
I know DAYSIM offered this and I think we can do a better implementation here in honeybee-radiance in that we can output a different schedule for each sensor grid (making it easily map-able to multiple rooms).  The only thing I would need to understand is how DAYSIM came up with assumptions for light-dimming. Did they just take the fraction of sensor grid points that were above the illuminance threshold and that became the fraction of the lights that dimmed?

**Comment by mostaphaRoudsari** [comment]
Hi @chriswmackey! This might help: https://github.com/MITSustainableDesignLab/Daysim/blob/master/src/daysim/ds_el_lighting.c

and this one: https://github.com/MITSustainableDesignLab/Daysim/blob/master/src/daysim/lightswitch.c

**Comment by chriswmackey** [comment]
This has been largely implemented on the front end.
