### ISSUE TITLE
Always write `grid` folder with `_info.json` file

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-radiance#494]
We should always write the `grid` folder and include the `_info.json` file even if there are no grid in the model. This makes the folder API a bit more consistent and avoids some bugs in the honeybee-radiance Pollination Plugin.

https://github.com/ladybug-tools/honeybee-radiance/blob/fae35ff1200f8a935e373d79ce38e9bdd4aa71da/honeybee_radiance/writer.py#L377-L397

**Comment by mostaphaRoudsari** [comment]
Hi @AntoineDao, the part of code that is shared above is for `views` - there is a similar portion for `grids`.

**Comment by AntoineDao** [comment]
I referenced the wrong section but had the right one in mind 🙃
