### ISSUE TITLE
Get the post-process group to display correctly in the CLI docs

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#508]
This is a minor issue for whenever @santiagogaray gets the chance. I can see that the `post-process` CLI group isn't displaying correctly in the docs:

![image](https://user-images.githubusercontent.com/5567574/113204485-4eefdb80-923b-11eb-9de2-aec1836b0085.png)

It seems like the group name is [being taken from the name of the group function](https://github.com/ladybug-tools/honeybee-radiance/blob/master/honeybee_radiance/cli/postprocess.py#L13) instead of [being taken from the click group name as it appears in the CLI](https://github.com/ladybug-tools/honeybee-radiance/blob/master/honeybee_radiance/cli/__init__.py#L65).

If it's possible to ensure that sphinx uses the CLI group name instead of the function name that would be ideal. Though I think all of the cases where the group name and function name would be different just involve replacing `_` with `-`. So, if it's much quicker to do a fix that way, that's also ok.

**Comment by santiagogaray** [comment]
Thanks @chriswmackey for finding yet another bug and sending those pointers, a learning experience! I think I should extract all these then from the __init__.py module to make sure we catch all these exceptions (same as ``mxtop``). That was the idea behind my approach, I happened to be looking in the wrong place.
By now you can tell how much I know about CLIs! :)

**Comment by chriswmackey** [comment]
Thanks @santiagogaray . This one has been resolved.
