### ISSUE TITLE
typing module - bug

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/honeybee-radiance#525]
Hi @mostaphaRoudsari,

I see that you recently started using the [typing](https://github.com/ladybug-tools/honeybee-radiance/blob/master/honeybee_radiance/writer.py#L3 ) module. This has however created [this](https://discourse.ladybug.tools/t/honeybee-radiance-cant-find-radiance/14110?u=devang). I could recreate this issue and I think it is happening since the grasshopper component is unable to locate the typing module.

**Comment by mostaphaRoudsari** [comment]
Ah! Python 2 happiness. This wasn't mean to be defaultdict as a type. I'll fix it later today. Thanks for reporting.
