### ISSUE TITLE
Add commands needed for Imageless Glare Recipe

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#641]
It seems like there is high demand for an imageless glare recipe as can be seen [in this forum post](https://discourse.ladybug.tools/t/annual-daylight-glare-probability-for-multiple-test-points/10889/23?u=chris).

Also, as that post shows, @mikkelkp has already demonstrated the commands that are needed to do it. So we can probably add some commands to do it with the new plugin. I imagine that we can accept a SensorGrid of points where people want to evaluate glare and then generate the various view directions in a circle around a central point.

**Comment by mikkelkp** [comment]
Closing this issue as it has been implemented.
