### ISSUE TITLE
Possible to edit API documentation? 

### ISSUE THREAD

**Issue by nimafo** [ladybug-tools/honeybee-radiance#768]
Hi all,
I am currently reading honeybee-radiance documentation API for my project, 
it is a very useful documentation, great job!
However, there are some typos here and there, like [*lear sky* instead of *clear sky*](https://www.ladybug.tools/honeybee-radiance/docs/cli/sky.html#honeybee-radiance-sky-leed-illuminance), or [*two* instead of *three*](https://www.ladybug.tools/honeybee-radiance/docs/cli/mtx.html#honeybee-radiance-mtxop-operate-three), 
I wonder if there is a way to contribute to the documentation by openly editing it as a viewer?

**Comment by mostaphaRoudsari** [comment]
Hi @nimafo! Thank you for offering help. The docs are created from the docstrings in the code. If you edit them directly in the documents there will be overwritten the next time that we push a new version.

To fix the issues, we have to fix them in the source code. FOr instance here is where the first issue is happening:
https://github.com/ladybug-tools/honeybee-radiance/blob/416661365491561a86f4c44a410d78d7adf52c2a/honeybee_radiance/cli/mtx.py#L151

And here is the second one:
https://github.com/ladybug-tools/honeybee-radiance/blob/416661365491561a86f4c44a410d78d7adf52c2a/honeybee_radiance/cli/sky.py#L398

If you don't feel comfortable with editing the docstrings and sending a PR, it will be helpful to list them here and we will fix them on your behalf.

**Comment by nimafo** [comment]
Great,
I think it will be convenient to edit from the source,
