### ISSUE TITLE
Problem with scene octree for DC calculation, (scene.oct): not an octree 

### ISSUE THREAD

**Issue by nimafo** [ladybug-tools/honeybee-radiance#769]
Hi all,
I face the following error when running `honeybee-radiance dc scoeff scene.oct model\grid\Grid_8a07902b.pts skydome.rad sky.mtx` CLI command in my model directory (attached .zip file):

> oconv: fatal - (scene.oct): not an octree
> rcontrib: fatal - (!oconv -f -i "scene.oct" ./skydome.rad): not an octree
> <stdin>: cannot load matrix

The octree is created by  `honeybee-radiance octree from-folder Examples\640_test\model > scene.oct`  command, which is the output folder from the command `honeybee-radiance translate model-to-rad-folder Examples\640_test.hbjson`.

Am I missing any step here?

[error.txt](https://github.com/ladybug-tools/honeybee-radiance/files/9314783/error.txt)
[ForumQuestion1.zip](https://github.com/ladybug-tools/honeybee-radiance/files/9314784/ForumQuestion1.zip)

**Comment by mostaphaRoudsari** [comment]
Hi @nimafo - you should post questions like this to the forum under the `scripting` category: https://discourse.ladybug.tools/c/scripting/28
